language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"

install :
    - pip install --user .  

script :
    - viman -Sf test.yml
    - viman -Rf test.yml

deploy:
    provider: pypi
    user: ${PYPI_USERNAME}
    password: ${PYPI_PASSWORD}

