language: python
python:
    - "3.5"
    - "3.6"

before_install :
    - pip install codecov

install :
    - pip install .  

script :
    - sudo apt-get update
    - export NATIVE_INSTALL='sudo apt-get install'
    - ./install.sh
    - coverage run viman -h
    - coverage run viman -V
    - coverage run viman -Q
    - coverage run viman -Sf test.yml
    - coverage run viman -Ur
    - coverage run viman -Rf test.yml

after_success :
    - codecov

deploy:
    provider: pypi
    user: ${PYPI_USERNAME}
    password: ${PYPI_PASSWORD}

