language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"

install :
    - pip install .  

script :
    - viman -h
    - viman -V
    - viman -Q
    - viman -Sf test.yml
    - viman -Rf test.yml

deploy:
    provider: pypi
    user: ${PYPI_USERNAME}
    password: ${PYPI_PASSWORD}

