language: python
python:
    - "3.5"
    - "3.6"

install :
    - pip install .  

script :
    - sudo apt-get update
    - export NATIVE_INSTALL='sudo apt-get install'
    - ./install.sh
    - viman -h
    - viman -V
    - viman -Q
    - viman -Sf test.yml
    - viman -Ur
    - viman -Rf test.yml

deploy:
    provider: pypi
    user: ${PYPI_USERNAME}
    password: ${PYPI_PASSWORD}

