language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"

before_install :
    - pip install codecov

install :
    - pip install .

script :
    - sudo apt-get update
    - export NATIVE_INSTALL='sudo apt-get install'
    - ./install.sh
    - coverage run ./viman/vimanApp.py -h
    - coverage run ./viman/vimanApp.py -V
    - coverage run ./viman/vimanApp.py -Q
    - coverage run ./viman/vimanApp.py -Sf test.yml
    - coverage run ./viman/vimanApp.py -Ur
    - coverage run ./viman/vimanApp.py -Rf test.yml

after_success :
    - codecov

deploy:
    provider: pypi
    user: ${PYPI_USERNAME}
    password: ${PYPI_PASSWORD}

